FROM node:14-slim 

WORKDIR /home/node/auto_request

COPY package*.json ./
RUN npm install

RUN apt-get install bash
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*
RUN wget -O /bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
RUN chmod +x /bin/wait-for-it.sh

COPY . .